service: default
runtime: nodejs12
env: standard
env_variables:
  APP_ENV: $APP_ENV
  SERVER_ROOT: $SERVER_ROOT
  SERVER_HOST: $SERVER_HOST
  JWT_SECRET: $JWT_SECRET
  JWT_EXPIRES_IN: $JWT_EXPIRES_IN
  MYSQL_HOST: $MYSQL_HOST
  MYSQL_PORT: $MYSQL_PORT
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  MYSQL_DATABASE: $MYSQL_DATABASE
  DB_SOCKET_PATH: $DB_SOCKET_PATH
  CLOUD_SQL_CONNECTION_NAME: $CLOUD_SQL_CONNECTION_NAME
  INTERCOM_ACCESS_TOKEN: $INTERCOM_ACCESS_TOKEN
  SWAGGER_TITLE: $SWAGGER_TITLE
  SWAGGER_DESCRIPTION: This is a simple CRUD API application made with Express and documented with Swagger
  SWAGGER_SERVER: $SWAGGER_SERVER
instance_class: F1
automatic_scaling:
  max_instances: 2
  min_instances: 0