# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy to production
    environment: production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Build project
      run: npm run build --if-present
    - uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
        SERVER_ROOT: /api
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        DB_SOCKET_PATH: ${{ secrets.DB_SOCKET_PATH }}
        CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
        INTERCOM_ACCESS_TOKEN: ${{ secrets.INTERCOM_ACCESS_TOKEN }}
        SWAGGER_TITLE: Moregooder API Reference
        SWAGGER_SERVER: ${{ secrets.SWAGGER_SERVER }}
    - name: Deploy to Production
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}