# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging CI

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: deploy to staging
    environment: staging
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Build project
      run: npm run build --if-present
    - name: Rename app-staging.yaml
      run: cp ./app-staging.yaml ./app.yaml
    - uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
        SERVER_ROOT: /api
        SERVER_HOST: https://staging-dot-moregooder.uc.r.appspot.com
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        FIRESTORE_USERS_COLLECTION: ${{ secrets.FIRESTORE_USERS_COLLECTION }}
        FIRESTORE_CONTACTS_COLLECTION: ${{ secrets.FIRESTORE_CONTACTS_COLLECTION }}
        SWAGGER_TITLE: Moregooder API Reference
        SWAGGER_SERVER: "https://staging-dot-moregooder.uc.r.appspot.com/api"
    - name: Deploy to Staging
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}